#!/usr/bin/env python3
import json

with open("/Users/joaoflores/Documents/GambitStudio/DevLingo/gen_pair_checkpoint.json") as f:
    phrases = json.load(f)

print(f"Loaded {len(phrases)} phrases")

# ============================================================
# EASY PHRASES 101-120: More basic pairing phrases
# ============================================================
data_easy_3 = [
("Let's pair on this.", "Proposing a pair programming session", "Vamos parear nisso.", "Vamos a hacer pair en esto.", "Faisons du pair programming là-dessus.", "Lass uns das zusammen programmieren.", "Facciamo pair programming su questo.", "これをペアプログラミングしましょう。", "이거 페어로 해요.", "我们一起结对编程吧。", "चलिए इस पर पेयर करते हैं।", "Bunu birlikte çalışalım."),
("Are you free to pair?", "Asking if someone is available for pairing", "Você está livre pra parear?", "¿Estás libre para hacer pair?", "Tu es dispo pour du pair ?", "Hast du Zeit zum Pairen?", "Sei libero per fare pair?", "ペアプログラミングできますか？", "페어할 시간 있어요?", "你有空结对吗？", "क्या आप पेयर करने के लिए फ़्री हैं?", "Eşli çalışmak için müsait misin?"),
("Good pairing session.", "Wrapping up a productive pairing session", "Boa sessão de pareamento.", "Buena sesión de pair.", "Bonne session de pair.", "Gute Pairing-Session.", "Buona sessione di pair.", "いいペアプログラミングでしたね。", "좋은 페어링 세션이었어요.", "很好的结对编程。", "अच्छा पेयरिंग सेशन रहा।", "İyi bir eşli çalışma oldu."),
("Thanks for pairing with me.", "Thanking your pair at the end of a session", "Obrigado por parear comigo.", "Gracias por hacer pair conmigo.", "Merci d'avoir pairé avec moi.", "Danke fürs Pairen mit mir.", "Grazie per aver fatto pair con me.", "ペアプログラミングありがとう。", "페어링해 줘서 감사해요.", "谢谢你和我结对。", "मेरे साथ पेयर करने के लिए धन्यवाद।", "Benimle eşli çalıştığın için teşekkürler."),
("Click on that tab.", "Directing the driver to a specific tab", "Clica naquela aba.", "Haz clic en esa pestaña.", "Clique sur cet onglet.", "Klick auf den Tab.", "Clicca su quella scheda.", "そのタブをクリックしてください。", "그 탭을 클릭해 주세요.", "点击那个标签。", "उस टैब पर क्लिक कीजिए।", "O sekmeye tıkla."),
("Try restarting the server.", "Suggesting a server restart to fix an issue", "Tenta reiniciar o servidor.", "Intenta reiniciar el servidor.", "Essaie de redémarrer le serveur.", "Versuch den Server neu zu starten.", "Prova a riavviare il server.", "サーバーを再起動してみてください。", "서버를 다시 시작해 보세요.", "试试重启服务器。", "सर्वर रीस्टार्ट करके देखिए।", "Sunucuyu yeniden başlatmayı dene."),
("Clear the cache.", "Suggesting clearing the cache to fix a bug", "Limpa o cache.", "Limpia el caché.", "Vide le cache.", "Lösche den Cache.", "Pulisci la cache.", "キャッシュをクリアしてください。", "캐시를 지워보세요.", "清一下缓存。", "कैश क्लियर कीजिए।", "Önbelleği temizle."),
("Add a breakpoint there.", "Suggesting where to add a debugging breakpoint", "Coloca um breakpoint ali.", "Agrega un breakpoint ahí.", "Mets un point d'arrêt là.", "Setze dort einen Breakpoint.", "Metti un breakpoint lì.", "そこにブレークポイントを置いてください。", "거기에 브레이크포인트를 걸어주세요.", "在那里加个断点。", "वहां एक ब्रेकपॉइंट लगाइए।", "Oraya bir kesme noktası ekle."),
("Step through it.", "Suggesting to use the debugger step-by-step", "Vai passo a passo.", "Recórrelo paso a paso.", "Avance pas à pas.", "Geh Schritt für Schritt durch.", "Procedi passo per passo.", "ステップ実行してみてください。", "한 단계씩 실행해 보세요.", "逐步执行。", "स्टेप बाय स्टेप चलाइए।", "Adım adım ilerle."),
("Log that value.", "Suggesting to add a console.log or print statement", "Loga esse valor.", "Imprime ese valor.", "Affiche cette valeur.", "Logge den Wert.", "Logga quel valore.", "その値をログに出してください。", "그 값을 로그로 찍어보세요.", "打印一下那个值。", "उस वैल्यू को लॉग कीजिए।", "O değeri logla."),
("What's the return type?", "Asking about a function's return type", "Qual o tipo de retorno?", "¿Cuál es el tipo de retorno?", "Quel est le type de retour ?", "Was ist der Rückgabetyp?", "Qual è il tipo di ritorno?", "戻り値の型は何ですか？", "리턴 타입이 뭐예요?", "返回类型是什么？", "रिटर्न टाइप क्या है?", "Dönüş tipi ne?"),
("Check the imports.", "Suggesting to review the import statements", "Verifica os imports.", "Revisa los imports.", "Vérifie les imports.", "Prüfe die Imports.", "Controlla gli import.", "インポートを確認してください。", "임포트를 확인해 보세요.", "检查一下导入。", "इम्पोर्ट्स चेक कीजिए।", "İmportları kontrol et."),
("We need to install that.", "Pointing out a missing dependency", "Precisamos instalar isso.", "Necesitamos instalar eso.", "Il faut installer ça.", "Wir müssen das installieren.", "Dobbiamo installarlo.", "それをインストールする必要があります。", "그걸 설치해야 해요.", "我们需要安装那个。", "हमें वो इंस्टॉल करना होगा।", "Onu kurmamız gerekiyor."),
("Pull the latest changes.", "Reminding to get the latest code from the repository", "Puxa as últimas mudanças.", "Baja los últimos cambios.", "Récupère les derniers changements.", "Hole die neuesten Änderungen.", "Scarica le ultime modifiche.", "最新の変更をプルしてください。", "최신 변경사항을 풀해주세요.", "拉取最新的更改。", "लेटेस्ट चेंजेस पुल कीजिए।", "Son değişiklikleri çek."),
("There's a merge conflict.", "Noticing a conflict during a merge or rebase", "Tem um conflito de merge.", "Hay un conflicto de merge.", "Il y a un conflit de merge.", "Es gibt einen Merge-Konflikt.", "C'è un conflitto di merge.", "マージコンフリクトがあります。", "머지 충돌이 있어요.", "有合并冲突。", "मर्ज कॉन्फ्लिक्ट है।", "Birleştirme çakışması var."),
("Let's resolve this conflict.", "Proposing to fix a merge conflict together", "Vamos resolver esse conflito.", "Resolvamos este conflicto.", "Résolvons ce conflit.", "Lass uns den Konflikt lösen.", "Risolviamo questo conflitto.", "このコンフリクトを解決しましょう。", "이 충돌을 해결해요.", "我们解决这个冲突吧。", "चलिए ये कॉन्फ्लिक्ट रिज़ॉल्व करते हैं।", "Bu çakışmayı çözelim."),
("Create a new branch.", "Suggesting to work on a new branch", "Cria uma branch nova.", "Crea una rama nueva.", "Crée une nouvelle branche.", "Erstelle einen neuen Branch.", "Crea un nuovo branch.", "新しいブランチを作りましょう。", "새 브랜치를 만드세요.", "创建一个新分支。", "एक नई ब्रांच बनाइए।", "Yeni bir dal oluştur."),
("Switch to that branch.", "Asking to check out a different branch", "Muda pra aquela branch.", "Cámbiate a esa rama.", "Bascule sur cette branche.", "Wechsle zu dem Branch.", "Passa a quel branch.", "そのブランチに切り替えてください。", "그 브랜치로 전환해 주세요.", "切换到那个分支。", "उस ब्रांच पर स्विच कीजिए।", "O dala geç."),
("Stash your changes.", "Suggesting to stash uncommitted work before switching branches", "Guarda suas mudanças no stash.", "Guarda tus cambios en stash.", "Mets tes changements en stash.", "Stashe deine Änderungen.", "Metti in stash le tue modifiche.", "変更をスタッシュしてください。", "변경사항을 스태시하세요.", "暂存你的更改。", "अपने चेंजेस स्टैश कीजिए।", "Değişikliklerini sakla."),
("I'll drive for this part.", "Volunteering to type for a specific section", "Eu digito essa parte.", "Yo conduzco en esta parte.", "Je pilote pour cette partie.", "Ich tippe für diesen Teil.", "Guido io per questa parte.", "この部分は私がタイプします。", "이 부분은 제가 드라이브할게요.", "这部分我来打字。", "इस हिस्से के लिए मैं ड्राइव करता हूं।", "Bu kısım için ben yazayım."),
]

for i, d in enumerate(data_easy_3, 101):
    phrases.append({
        "id": f"pairProgramming_{i:03d}",
        "english": d[0],
        "context": d[1],
        "translations": {
            "pt-BR": d[2], "es": d[3], "fr": d[4], "de": d[5],
            "it": d[6], "ja": d[7], "ko": d[8], "zh-Hans": d[9],
            "hi": d[10], "tr": d[11]
        },
        "difficulty": "easy",
        "category": "pairProgramming"
    })

print(f"After easy batch 3: {len(phrases)} phrases")

# ============================================================
# MEDIUM PHRASES 121-180: Suggesting approaches & debugging
# ============================================================
data_med_1 = [
("I think we should extract this into a separate function.", "Suggesting a refactor to improve code organization", "Acho que devemos extrair isso pra uma função separada.", "Creo que deberíamos extraer esto en una función separada.", "Je pense qu'on devrait extraire ça dans une fonction séparée.", "Ich denke, wir sollten das in eine separate Funktion auslagern.", "Penso che dovremmo estrarre questo in una funzione separata.", "これを別の関数に抽出すべきだと思います。", "이걸 별도의 함수로 분리해야 할 것 같아요.", "我觉得我们应该把这部分提取成一个单独的函数。", "मुझे लगता है हमें इसे एक अलग फ़ंक्शन में निकालना चाहिए।", "Bunu ayrı bir fonksiyona çıkarmamız gerektiğini düşünüyorum."),
("We could use a map here instead of a for loop.", "Suggesting a more functional approach", "Podemos usar um map aqui em vez de um for loop.", "Podríamos usar un map aquí en vez de un for loop.", "On pourrait utiliser un map ici au lieu d'une boucle for.", "Wir könnten hier eine Map statt einer for-Schleife verwenden.", "Potremmo usare una map qui invece di un ciclo for.", "forループの代わりにmapを使えます。", "for 루프 대신 map을 쓸 수 있어요.", "这里可以用 map 代替 for 循环。", "यहां for loop की जगह map इस्तेमाल कर सकते हैं।", "Burada for döngüsü yerine map kullanabiliriz."),
("Let's add some error handling for this edge case.", "Identifying a missing error handler", "Vamos adicionar tratamento de erro pra esse caso limite.", "Agreguemos manejo de errores para este caso límite.", "Ajoutons une gestion d'erreur pour ce cas limite.", "Lass uns Fehlerbehandlung für diesen Grenzfall hinzufügen.", "Aggiungiamo la gestione degli errori per questo caso limite.", "このエッジケースにエラーハンドリングを追加しましょう。", "이 에지 케이스에 에러 핸들링을 추가해요.", "我们给这个边界情况加个错误处理吧。", "इस एज केस के लिए एरर हैंडलिंग जोड़ते हैं।", "Bu uç durum için hata yönetimi ekleyelim."),
("This variable name doesn't clearly describe what it holds.", "Suggesting a more descriptive variable name", "Esse nome de variável não descreve bem o que ela guarda.", "Este nombre de variable no describe claramente lo que contiene.", "Ce nom de variable ne décrit pas clairement ce qu'il contient.", "Dieser Variablenname beschreibt nicht klar, was er enthält.", "Questo nome di variabile non descrive chiaramente cosa contiene.", "この変数名は中身を明確に表していません。", "이 변수 이름이 무엇을 담고 있는지 명확하지 않아요.", "这个变量名不太能描述它存储的内容。", "ये वेरिएबल नाम अच्छे से नहीं बताता कि इसमें क्या है।", "Bu değişken adı içerdiğini net olarak tanımlamıyor."),
("I wonder if there's a built-in method for this.", "Speculating about existing utility methods", "Será que tem um método nativo pra isso?", "Me pregunto si hay un método nativo para esto.", "Je me demande s'il y a une méthode native pour ça.", "Ich frage mich, ob es dafür eine eingebaute Methode gibt.", "Mi chiedo se esiste un metodo integrato per questo.", "これに組み込みメソッドがあるかもしれません。", "이거 내장 메서드가 있을지 궁금해요.", "不知道有没有内置方法可以做这个。", "सोच रहा हूं इसके लिए कोई built-in मेथड होगा क्या।", "Bunun için yerleşik bir yöntem var mı acaba."),
("We should handle the null case here.", "Pointing out potential null pointer issues", "Devemos tratar o caso nulo aqui.", "Deberíamos manejar el caso nulo aquí.", "On devrait gérer le cas null ici.", "Wir sollten hier den Null-Fall behandeln.", "Dovremmo gestire il caso null qui.", "ここでnullケースを処理すべきです。", "여기서 null 케이스를 처리해야 해요.", "这里应该处理 null 的情况。", "यहां null केस हैंडल करना चाहिए।", "Burada null durumunu ele almalıyız."),
("Can we make this function more generic?", "Suggesting increased reusability", "Podemos tornar essa função mais genérica?", "¿Podemos hacer esta función más genérica?", "On peut rendre cette fonction plus générique ?", "Können wir diese Funktion generischer machen?", "Possiamo rendere questa funzione più generica?", "この関数をもっと汎用的にできますか？", "이 함수를 더 범용적으로 만들 수 있을까요?", "能把这个函数做得更通用吗？", "क्या इस फ़ंक्शन को और जेनेरिक बना सकते हैं?", "Bu fonksiyonu daha genel yapabilir miyiz?"),
("This is tightly coupled. Let's try to decouple it.", "Identifying code coupling issues", "Isso está muito acoplado. Vamos tentar desacoplar.", "Esto está muy acoplado. Intentemos desacoplarlo.", "C'est très couplé. Essayons de découpler ça.", "Das ist eng gekoppelt. Lass uns das entkoppeln.", "Questo è troppo accoppiato. Proviamo a disaccoppiarlo.", "これは密結合です。疎結合にしましょう。", "이건 결합도가 높아요. 분리해 봐요.", "这个耦合度太高了，我们解耦一下。", "ये टाइटली कपल्ड है। डीकपल करने की कोशिश करते हैं।", "Bu sıkı bağlı. Ayırmayı deneyelim."),
("The state management here is getting messy.", "Identifying complex state logic during pairing", "O gerenciamento de estado aqui está ficando bagunçado.", "La gestión del estado aquí se está desordenando.", "La gestion de l'état devient bordélique ici.", "Das State-Management wird hier unordentlich.", "La gestione dello stato qui sta diventando caotica.", "ここの状態管理がごちゃごちゃしてきました。", "여기 상태 관리가 복잡해지고 있어요.", "这里的状态管理变得混乱了。", "यहां स्टेट मैनेजमेंट गड़बड़ हो रहा है।", "Buradaki durum yönetimi karışıyor."),
("Let me trace through the logic step by step.", "Methodically following the code execution path", "Deixa eu rastrear a lógica passo a passo.", "Déjame seguir la lógica paso a paso.", "Laisse-moi suivre la logique étape par étape.", "Lass mich die Logik Schritt für Schritt durchgehen.", "Fammi seguire la logica passo per passo.", "ロジックをステップバイステップで追ってみます。", "로직을 단계별로 따라가 볼게요.", "让我一步步追踪这个逻辑。", "मुझे लॉजिक स्टेप बाय स्टेप ट्रेस करने दीजिए।", "Mantığı adım adım takip edeyim."),
("I think the issue is in how we're passing props.", "Identifying a props-related bug in UI code", "Acho que o problema é em como estamos passando as props.", "Creo que el problema está en cómo pasamos las props.", "Je pense que le problème vient de la façon dont on passe les props.", "Ich glaube, das Problem liegt darin, wie wir Props übergeben.", "Penso che il problema sia nel modo in cui passiamo le props.", "propsの渡し方に問題があると思います。", "props를 전달하는 방식에 문제가 있는 것 같아요.", "我觉得问题出在我们传 props 的方式上。", "मुझे लगता है समस्या props पास करने के तरीके में है।", "Sorun props'ları nasıl geçirdiğimizde galiba."),
("This component is doing too much. Let's split it.", "Suggesting component decomposition", "Esse componente está fazendo coisa demais. Vamos dividir.", "Este componente está haciendo demasiado. Dividámoslo.", "Ce composant en fait trop. Séparons-le.", "Diese Komponente macht zu viel. Lass sie uns aufteilen.", "Questo componente fa troppo. Dividiamolo.", "このコンポーネントはやりすぎています。分割しましょう。", "이 컴포넌트가 너무 많은 일을 해요. 나누자.", "这个组件做的事情太多了，拆分一下吧。", "ये कॉम्पोनेंट बहुत ज़्यादा कर रहा है। स्प्लिट करते हैं।", "Bu bileşen çok fazla iş yapıyor. Bölelim."),
("Shouldn't this be async?", "Questioning whether a function needs to be asynchronous", "Isso não deveria ser assíncrono?", "¿No debería ser async esto?", "Ça ne devrait pas être async ?", "Sollte das nicht async sein?", "Non dovrebbe essere async?", "これはasyncにすべきでは？", "이건 비동기여야 하지 않나요?", "这个不应该是异步的吗？", "क्या ये async नहीं होना चाहिए?", "Bu async olması gerekmiyor mu?"),
("We're not awaiting this promise.", "Spotting a missing await keyword", "Não estamos dando await nessa promise.", "No estamos haciendo await de esta promesa.", "On n'attend pas cette promesse.", "Wir awaiten dieses Promise nicht.", "Non stiamo facendo await di questa promise.", "このPromiseをawaitしていません。", "이 프로미스를 await 하고 있지 않아요.", "我们没有 await 这个 promise。", "हम इस promise को await नहीं कर रहे।", "Bu promise'i await etmiyoruz."),
("There might be a race condition here.", "Identifying potential concurrency issues", "Pode ter uma race condition aqui.", "Puede haber una condición de carrera aquí.", "Il pourrait y avoir une race condition ici.", "Hier könnte eine Race Condition sein.", "Potrebbe esserci una race condition qui.", "ここにレースコンディションがあるかもしれません。", "여기 레이스 컨디션이 있을 수 있어요.", "这里可能有竞态条件。", "यहां रेस कंडीशन हो सकती है।", "Burada bir yarış durumu olabilir."),
("Let's add a guard clause at the top.", "Suggesting early return to simplify logic", "Vamos adicionar uma cláusula de guarda no início.", "Agreguemos una cláusula de guarda al inicio.", "Ajoutons une clause de garde au début.", "Lass uns oben eine Guard-Klausel hinzufügen.", "Aggiungiamo una guard clause all'inizio.", "先頭にガード句を追加しましょう。", "맨 위에 가드 절을 추가해요.", "在顶部加一个守卫子句吧。", "ऊपर एक गार्ड क्लॉज़ जोड़ते हैं।", "Başa bir koruma cümlesi ekleyelim."),
("Can you walk me through your thought process?", "Asking the driver to explain their reasoning", "Pode me explicar seu raciocínio?", "¿Puedes explicarme tu proceso de pensamiento?", "Tu peux m'expliquer ton raisonnement ?", "Kannst du mir deinen Gedankengang erklären?", "Puoi spiegarmi il tuo ragionamento?", "考えのプロセスを説明してもらえますか？", "당신의 사고 과정을 설명해 줄 수 있어요?", "你能说说你的思路吗？", "क्या आप अपनी सोच की प्रक्रिया बता सकते हैं?", "Düşünce sürecini bana anlatır mısın?"),
("Let me think about the data flow for a second.", "Pausing to consider how data moves through the system", "Deixa eu pensar no fluxo de dados um segundo.", "Déjame pensar en el flujo de datos un momento.", "Laisse-moi réfléchir au flux de données un instant.", "Lass mich kurz über den Datenfluss nachdenken.", "Fammi pensare al flusso dei dati un attimo.", "データフローについて少し考えさせてください。", "데이터 흐름에 대해 잠깐 생각해 볼게요.", "让我想一下数据流。", "मुझे डेटा फ़्लो के बारे में एक सेकंड सोचने दीजिए।", "Veri akışı hakkında bir saniye düşüneyim."),
("I think we have a circular dependency here.", "Identifying a circular import or reference issue", "Acho que temos uma dependência circular aqui.", "Creo que tenemos una dependencia circular aquí.", "Je pense qu'on a une dépendance circulaire ici.", "Ich glaube, wir haben hier eine zirkuläre Abhängigkeit.", "Penso che abbiamo una dipendenza circolare qui.", "ここに循環依存があると思います。", "여기 순환 의존성이 있는 것 같아요.", "我觉得这里有循环依赖。", "मुझे लगता है यहां सर्कुलर डिपेंडेंसी है।", "Burada döngüsel bir bağımlılık var galiba."),
("We should probably add a loading state for this.", "Suggesting UX improvement for async operations", "Devemos provavelmente adicionar um estado de carregamento.", "Probablemente deberíamos agregar un estado de carga.", "On devrait probablement ajouter un état de chargement.", "Wir sollten wahrscheinlich einen Ladezustand hinzufügen.", "Dovremmo probabilmente aggiungere uno stato di caricamento.", "これにローディング状態を追加すべきですね。", "이거 로딩 상태를 추가해야 할 것 같아요.", "我们可能需要加个加载状态。", "शायद इसके लिए एक लोडिंग स्टेट जोड़ना चाहिए।", "Bunun için bir yükleme durumu eklemeliyiz muhtemelen."),
("This API call doesn't have any retry logic.", "Identifying missing resilience patterns", "Essa chamada de API não tem lógica de retry.", "Esta llamada a la API no tiene lógica de reintentos.", "Cet appel API n'a pas de logique de retry.", "Dieser API-Aufruf hat keine Retry-Logik.", "Questa chiamata API non ha logica di retry.", "このAPI呼び出しにリトライロジックがありません。", "이 API 호출에 재시도 로직이 없어요.", "这个 API 调用没有重试逻辑。", "इस API कॉल में कोई retry लॉजिक नहीं है।", "Bu API çağrısında yeniden deneme mantığı yok."),
("Let's write a unit test for this edge case.", "Suggesting targeted test coverage", "Vamos escrever um teste unitário pra esse caso limite.", "Escribamos un test unitario para este caso límite.", "Écrivons un test unitaire pour ce cas limite.", "Lass uns einen Unit-Test für diesen Grenzfall schreiben.", "Scriviamo un unit test per questo caso limite.", "このエッジケースのユニットテストを書きましょう。", "이 에지 케이스에 대한 유닛 테스트를 작성해요.", "给这个边界情况写个单元测试吧。", "इस एज केस के लिए यूनिट टेस्ट लिखते हैं।", "Bu uç durum için bir birim testi yazalım."),
("The test is flaky — it passes sometimes and fails other times.", "Describing an unreliable test", "O teste é instável — às vezes passa e às vezes falha.", "El test es inestable — a veces pasa y a veces falla.", "Le test est instable — il passe parfois et échoue d'autres fois.", "Der Test ist flaky — er besteht manchmal und schlägt manchmal fehl.", "Il test è instabile — a volte passa e a volte no.", "テストが不安定で、通るときと失敗するときがあります。", "테스트가 불안정해요 — 때때로 통과하고 때때로 실패해요.", "测试不稳定——有时通过有时失败。", "टेस्ट फ्लेकी है — कभी पास होता है कभी फेल।", "Test kararsız — bazen geçiyor bazen başarısız oluyor."),
("Should we mock this dependency in the test?", "Discussing test isolation strategy", "Devemos mockar essa dependência no teste?", "¿Deberíamos mockear esta dependencia en el test?", "On devrait mocker cette dépendance dans le test ?", "Sollen wir diese Abhängigkeit im Test mocken?", "Dovremmo fare il mock di questa dipendenza nel test?", "テストでこの依存関係をモックすべきですか？", "테스트에서 이 의존성을 목으로 만들어야 할까요?", "测试中要 mock 这个依赖吗？", "क्या टेस्ट में इस डिपेंडेंसी को mock करना चाहिए?", "Testte bu bağımlılığı mock'lamalı mıyız?"),
("I think the issue is in the callback closure.", "Identifying a closure-related bug", "Acho que o problema está no closure do callback.", "Creo que el problema está en el closure del callback.", "Je pense que le problème est dans la closure du callback.", "Ich glaube, das Problem liegt in der Callback-Closure.", "Penso che il problema sia nella closure del callback.", "コールバッククロージャに問題があると思います。", "콜백 클로저에 문제가 있는 것 같아요.", "我觉得问题出在回调的闭包上。", "मुझे लगता है समस्या कॉलबैक क्लोज़र में है।", "Sorunun callback closure'da olduğunu düşünüyorum."),
("We should debounce this input handler.", "Suggesting performance improvement for user input", "Devemos fazer debounce nesse handler de input.", "Deberíamos hacer debounce de este manejador de input.", "On devrait faire un debounce de ce gestionnaire d'input.", "Wir sollten diesen Input-Handler debouncen.", "Dovremmo fare il debounce di questo handler dell'input.", "この入力ハンドラーにデバウンスを追加すべきです。", "이 인풋 핸들러에 디바운스를 걸어야 해요.", "我们应该对这个输入处理器做防抖。", "इस इनपुट हैंडलर को डिबाउंस करना चाहिए।", "Bu girdi işleyicisini debounce etmeliyiz."),
("I notice this effect runs on every render.", "Spotting a performance issue in React or similar framework", "Percebi que esse efeito roda em todo render.", "Noto que este efecto se ejecuta en cada renderizado.", "Je remarque que cet effet s'exécute à chaque rendu.", "Mir fällt auf, dass dieser Effekt bei jedem Render läuft.", "Noto che questo effetto viene eseguito ad ogni render.", "このエフェクトが毎回のレンダリングで実行されています。", "이 이펙트가 매 렌더링마다 실행되고 있어요.", "我注意到这个 effect 每次渲染都在运行。", "मैंने देखा कि ये effect हर रेंडर पर चलता है।", "Bu etkinin her render'da çalıştığını fark ettim."),
("The dependency array is missing some values.", "Identifying a stale closure issue in hooks", "O array de dependências está faltando alguns valores.", "Al array de dependencias le faltan algunos valores.", "Le tableau de dépendances manque certaines valeurs.", "Dem Dependency-Array fehlen einige Werte.", "All'array delle dipendenze mancano alcuni valori.", "依存配列にいくつかの値が不足しています。", "의존성 배열에 값이 빠져 있어요.", "依赖数组缺少一些值。", "डिपेंडेंसी एरे में कुछ वैल्यूज़ मिसिंग हैं।", "Bağımlılık dizisinde bazı değerler eksik."),
("Let's memoize this expensive computation.", "Suggesting caching for performance", "Vamos memoizar esse cálculo pesado.", "Vamos a memoizar este cálculo costoso.", "Mémoïsons ce calcul coûteux.", "Lass uns diese teure Berechnung memoisieren.", "Memorizziamo questo calcolo costoso.", "この重い計算をメモ化しましょう。", "이 비용이 큰 연산을 메모이제이션해요.", "把这个开销大的计算做个缓存吧。", "इस महंगी कम्प्यूटेशन को मेमोइज़ करते हैं।", "Bu pahalı hesaplamayı önbelleğe alalım."),
("This could cause a memory leak if we don't clean up.", "Warning about resource cleanup", "Isso pode causar vazamento de memória se não limparmos.", "Esto podría causar una fuga de memoria si no limpiamos.", "Ça pourrait causer une fuite mémoire si on ne nettoie pas.", "Das könnte ein Speicherleck verursachen, wenn wir nicht aufräumen.", "Questo potrebbe causare un memory leak se non puliamo.", "クリーンアップしないとメモリリークの原因になります。", "정리하지 않으면 메모리 누수가 생길 수 있어요.", "如果不清理可能会导致内存泄漏。", "अगर क्लीनअप नहीं करेंगे तो मेमोरी लीक हो सकती है।", "Temizlemezsek bellek sızıntısına neden olabilir."),
("Let me check if this API endpoint exists yet.", "Verifying backend availability before frontend work", "Deixa eu verificar se esse endpoint de API já existe.", "Déjame verificar si este endpoint de API ya existe.", "Laisse-moi vérifier si cet endpoint d'API existe déjà.", "Lass mich prüfen, ob dieser API-Endpunkt schon existiert.", "Fammi verificare se questo endpoint API esiste già.", "このAPIエンドポイントが既に存在するか確認させてください。", "이 API 엔드포인트가 있는지 확인해 볼게요.", "让我看看这个 API 端点是否已经存在。", "मुझे चेक करने दीजिए कि ये API एंडपॉइंट मौजूद है या नहीं।", "Bu API uç noktasının var olup olmadığını kontrol edeyim."),
("I think the problem is on the backend, not the frontend.", "Narrowing down where a bug originates", "Acho que o problema é no backend, não no frontend.", "Creo que el problema está en el backend, no en el frontend.", "Je pense que le problème est côté backend, pas frontend.", "Ich glaube, das Problem liegt am Backend, nicht am Frontend.", "Penso che il problema sia nel backend, non nel frontend.", "問題はフロントエンドではなくバックエンドにあると思います。", "문제는 프론트엔드가 아니라 백엔드에 있는 것 같아요.", "我觉得问题在后端，不在前端。", "मुझे लगता है समस्या बैकएंड में है, फ़्रंटएंड में नहीं।", "Sorunun frontend'de değil backend'de olduğunu düşünüyorum."),
("Can we check the network tab to see the response?", "Using browser dev tools during debugging", "Podemos verificar a aba de rede pra ver a resposta?", "¿Podemos revisar la pestaña de red para ver la respuesta?", "On peut vérifier l'onglet réseau pour voir la réponse ?", "Können wir im Netzwerk-Tab die Antwort prüfen?", "Possiamo controllare la scheda network per vedere la risposta?", "ネットワークタブでレスポンスを確認できますか？", "네트워크 탭에서 응답을 확인해 볼까요?", "能看一下网络标签里的响应吗？", "क्या हम नेटवर्क टैब में रिस्पॉन्स देख सकते हैं?", "Yanıtı görmek için ağ sekmesini kontrol edebilir miyiz?"),
("The response payload looks different from what we expected.", "Noticing unexpected API response data", "O payload da resposta parece diferente do esperado.", "El payload de la respuesta se ve diferente de lo esperado.", "Le payload de la réponse est différent de ce qu'on attendait.", "Die Antwort-Payload sieht anders aus als erwartet.", "Il payload della risposta sembra diverso da quello che ci aspettavamo.", "レスポンスのペイロードが想定と異なっています。", "응답 페이로드가 예상과 다르게 보여요.", "响应数据和我们预期的不一样。", "रिस्पॉन्स पेलोड हमारी अपेक्षा से अलग दिख रहा है।", "Yanıt verisi beklediğimizden farklı görünüyor."),
("Let's console.log this object to see its structure.", "Using logging to inspect data during debugging", "Vamos dar console.log nesse objeto pra ver a estrutura.", "Vamos hacer console.log de este objeto para ver su estructura.", "Faisons un console.log de cet objet pour voir sa structure.", "Lass uns das Objekt loggen, um seine Struktur zu sehen.", "Facciamo console.log di questo oggetto per vedere la struttura.", "このオブジェクトをconsole.logで構造を確認しましょう。", "이 객체를 console.log로 찍어서 구조를 봐요.", "console.log 一下这个对象，看看它的结构。", "इस ऑब्जेक्ट को console.log करके स्ट्रक्चर देखते हैं।", "Yapısını görmek için bu nesneyi console.log ile yazdıralım."),
("The error stack trace points to this line.", "Analyzing an error trace during debugging", "O stack trace do erro aponta pra essa linha.", "El stack trace del error apunta a esta línea.", "La stack trace de l'erreur pointe vers cette ligne.", "Der Error-Stack-Trace zeigt auf diese Zeile.", "Lo stack trace dell'errore punta a questa riga.", "エラースタックトレースがこの行を指しています。", "에러 스택 트레이스가 이 줄을 가리키고 있어요.", "错误堆栈追踪指向了这一行。", "एरर स्टैक ट्रेस इस लाइन को पॉइंट कर रहा है।", "Hata yığın izi bu satırı gösteriyor."),
("I think we need to add TypeScript types to this.", "Suggesting type safety improvements", "Acho que precisamos adicionar tipos TypeScript nisso.", "Creo que necesitamos agregar tipos TypeScript a esto.", "Je pense qu'on devrait ajouter des types TypeScript ici.", "Ich denke, wir sollten TypeScript-Typen hinzufügen.", "Penso che dobbiamo aggiungere i tipi TypeScript.", "これにTypeScriptの型を追加する必要があると思います。", "이거 TypeScript 타입을 추가해야 할 것 같아요.", "我觉得需要给这个加上 TypeScript 类型。", "मुझे लगता है इसमें TypeScript टाइप्स जोड़ने होंगे।", "Buna TypeScript tipleri eklememiz gerektiğini düşünüyorum."),
("Should we handle the loading, error, and success states?", "Discussing complete async state handling", "Devemos tratar os estados de carregamento, erro e sucesso?", "¿Deberíamos manejar los estados de carga, error y éxito?", "On devrait gérer les états de chargement, erreur et succès ?", "Sollen wir Loading-, Error- und Success-States behandeln?", "Dovremmo gestire gli stati di caricamento, errore e successo?", "ローディング、エラー、成功の状態を処理すべきですか？", "로딩, 에러, 성공 상태를 모두 처리해야 할까요?", "要处理加载、错误和成功状态吗？", "क्या हमें लोडिंग, एरर और सक्सेस स्टेट्स हैंडल करने चाहिए?", "Yükleme, hata ve başarı durumlarını ele almalı mıyız?"),
("Let me add proper error boundaries around this.", "Implementing error handling for component failures", "Deixa eu adicionar error boundaries corretas ao redor disso.", "Déjame agregar error boundaries adecuados alrededor de esto.", "Laisse-moi ajouter des error boundaries ici.", "Lass mich hier ordentliche Error Boundaries hinzufügen.", "Fammi aggiungere degli error boundary adeguati.", "適切なエラーバウンダリーを追加させてください。", "이 주변에 에러 바운더리를 제대로 추가할게요.", "让我在这周围加上适当的错误边界。", "मुझे इसके आसपास proper error boundaries जोड़ने दीजिए।", "Bunun etrafına uygun hata sınırları ekleyeyim."),
("We should validate the input before processing it.", "Suggesting input validation", "Devemos validar o input antes de processá-lo.", "Deberíamos validar la entrada antes de procesarla.", "On devrait valider l'entrée avant de la traiter.", "Wir sollten die Eingabe validieren, bevor wir sie verarbeiten.", "Dovremmo validare l'input prima di elaborarlo.", "処理する前に入力を検証すべきです。", "처리하기 전에 입력을 검증해야 해요.", "处理之前应该先验证输入。", "प्रोसेस करने से पहले इनपुट वैलिडेट करना चाहिए।", "İşlemden önce girdiyi doğrulamalıyız."),
("What happens if this request times out?", "Considering timeout scenarios", "O que acontece se essa requisição der timeout?", "¿Qué pasa si esta petición expira?", "Que se passe-t-il si cette requête expire ?", "Was passiert, wenn diese Anfrage ein Timeout hat?", "Cosa succede se questa richiesta va in timeout?", "このリクエストがタイムアウトしたらどうなりますか？", "이 요청이 타임아웃되면 어떻게 돼요?", "如果这个请求超时了会怎样？", "अगर ये रिक्वेस्ट टाइमआउट हो गई तो क्या होगा?", "Bu istek zaman aşımına uğrarsa ne olur?"),
("We should add pagination to this list.", "Suggesting performance improvement for large lists", "Devemos adicionar paginação nessa lista.", "Deberíamos agregar paginación a esta lista.", "On devrait ajouter de la pagination à cette liste.", "Wir sollten Paginierung für diese Liste hinzufügen.", "Dovremmo aggiungere la paginazione a questa lista.", "このリストにページネーションを追加すべきです。", "이 리스트에 페이지네이션을 추가해야 해요.", "我们应该给这个列表加分页。", "इस लिस्ट में पेजिनेशन जोड़ना चाहिए।", "Bu listeye sayfalama eklemeliyiz."),
]

for i, d in enumerate(data_med_1, 121):
    phrases.append({
        "id": f"pairProgramming_{i:03d}",
        "english": d[0],
        "context": d[1],
        "translations": {
            "pt-BR": d[2], "es": d[3], "fr": d[4], "de": d[5],
            "it": d[6], "ja": d[7], "ko": d[8], "zh-Hans": d[9],
            "hi": d[10], "tr": d[11]
        },
        "difficulty": "medium",
        "category": "pairProgramming"
    })

print(f"After medium batch 1: {len(phrases)} phrases")

with open("/Users/joaoflores/Documents/GambitStudio/DevLingo/gen_pair_checkpoint.json", "w") as f:
    json.dump(phrases, f)
print("Checkpoint saved")
