#!/usr/bin/env python3
import json

phrases = []

# ============================================================
# EASY PHRASES 1-60: Driver/Navigator roles & sharing screen
# ============================================================
data_easy_1 = [
("Do you want to drive or should I?", "Deciding who types during a pair programming session", "Você quer digitar ou eu digito?", "¿Quieres conducir o lo hago yo?", "Tu veux piloter ou je le fais ?", "Willst du tippen oder soll ich?", "Vuoi guidare tu o guido io?", "あなたがタイプしますか、それとも私がしましょうか？", "당신이 타이핑할래요, 아니면 제가 할까요?", "你来打字还是我来？", "आप टाइप करना चाहेंगे या मैं करूं?", "Sen mi yazmak istersin yoksa ben mi yazayım?"),
("I'll drive, you navigate.", "Assigning roles at the start of a pairing session", "Eu digito, você navega.", "Yo conduzco, tú navegas.", "Je pilote, tu navigues.", "Ich tippe, du navigierst.", "Io guido, tu navighi.", "私がタイプして、あなたがナビゲートしてください。", "제가 타이핑할게요, 당신이 네비게이트해주세요.", "我来打字，你来导航。", "मैं टाइप करता हूं, आप नेविगेट करें।", "Ben yazayım, sen yönlendir."),
("Let me share my screen.", "Starting a pair programming session by sharing your screen", "Deixa eu compartilhar minha tela.", "Déjame compartir mi pantalla.", "Laisse-moi partager mon écran.", "Lass mich meinen Bildschirm teilen.", "Fammi condividere il mio schermo.", "画面を共有させてください。", "제 화면을 공유할게요.", "让我共享一下屏幕。", "मुझे अपनी स्क्रीन शेयर करने दीजिए।", "Ekranımı paylaşayım."),
("Can you see my screen?", "Confirming the other person can see your shared screen", "Você consegue ver minha tela?", "¿Puedes ver mi pantalla?", "Tu vois mon écran ?", "Kannst du meinen Bildschirm sehen?", "Riesci a vedere il mio schermo?", "画面は見えますか？", "제 화면 보이세요?", "你能看到我的屏幕吗？", "क्या आप मेरी स्क्रीन देख पा रहे हैं?", "Ekranımı görebiliyor musun?"),
("Your turn to drive.", "Switching driver/navigator roles", "Sua vez de digitar.", "Tu turno de conducir.", "À ton tour de piloter.", "Du bist dran mit Tippen.", "Tocca a te guidare.", "あなたがタイプする番です。", "이제 당신이 타이핑할 차례예요.", "轮到你来打字了。", "अब आपकी बारी है टाइप करने की।", "Senin yazma sıran."),
("Let's swap roles.", "Suggesting a switch between driver and navigator", "Vamos trocar de papéis.", "Intercambiemos roles.", "Échangeons les rôles.", "Lass uns die Rollen tauschen.", "Scambiamoci i ruoli.", "役割を交代しましょう。", "역할을 바꿔요.", "我们换一下角色吧。", "चलिए भूमिकाएं बदलते हैं।", "Rolleri değiştirelim."),
("I can see it now, thanks.", "Confirming you can see the shared screen", "Agora estou vendo, obrigado.", "Ya lo veo, gracias.", "Je le vois maintenant, merci.", "Ich sehe es jetzt, danke.", "Ora lo vedo, grazie.", "見えました、ありがとう。", "이제 보여요, 감사합니다.", "我现在能看到了，谢谢。", "अब दिख रहा है, धन्यवाद।", "Şimdi görebiliyorum, teşekkürler."),
("Can you zoom in a bit?", "Asking the driver to enlarge the code on screen", "Pode dar um zoom?", "¿Puedes hacer zoom?", "Tu peux zoomer un peu ?", "Kannst du etwas reinzoomen?", "Puoi ingrandire un po'?", "少しズームしてもらえますか？", "좀 확대해 줄 수 있어요?", "能放大一点吗？", "क्या आप थोड़ा ज़ूम इन कर सकते हैं?", "Biraz yakınlaştırabilir misin?"),
("Let me increase the font size.", "Making the code more readable for the navigator", "Deixa eu aumentar a fonte.", "Déjame aumentar el tamaño de fuente.", "Laisse-moi agrandir la police.", "Lass mich die Schriftgröße erhöhen.", "Fammi aumentare la dimensione del font.", "フォントサイズを大きくしますね。", "글꼴 크기를 키울게요.", "我把字体调大一点。", "मैं फ़ॉन्ट साइज़ बढ़ा देता हूं।", "Yazı tipi boyutunu büyüteyim."),
("Scroll down a little.", "Asking the driver to scroll to see more code", "Desce um pouco.", "Baja un poco.", "Descends un peu.", "Scroll mal ein bisschen runter.", "Scorri un po' giù.", "少し下にスクロールしてください。", "조금 아래로 스크롤해 주세요.", "往下滚动一点。", "थोड़ा नीचे स्क्रॉल कीजिए।", "Biraz aşağı kaydır."),
("Go back to that file.", "Asking the driver to navigate to a previously opened file", "Volta pra aquele arquivo.", "Vuelve a ese archivo.", "Retourne à ce fichier.", "Geh zurück zu der Datei.", "Torna a quel file.", "あのファイルに戻ってください。", "그 파일로 돌아가 주세요.", "回到那个文件。", "उस फ़ाइल पर वापस जाइए।", "O dosyaya geri dön."),
("Which file are we in?", "Asking the driver to clarify the current file", "Em qual arquivo estamos?", "¿En qué archivo estamos?", "On est dans quel fichier ?", "In welcher Datei sind wir?", "In quale file siamo?", "今どのファイルにいますか？", "지금 어떤 파일에 있어요?", "我们在哪个文件里？", "हम किस फ़ाइल में हैं?", "Hangi dosyadayız?"),
("Open the terminal.", "Asking the driver to open a terminal window", "Abre o terminal.", "Abre la terminal.", "Ouvre le terminal.", "Öffne das Terminal.", "Apri il terminale.", "ターミナルを開いてください。", "터미널을 열어주세요.", "打开终端。", "टर्मिनल खोलिए।", "Terminali aç."),
("Run the tests.", "Asking the driver to execute the test suite", "Roda os testes.", "Ejecuta los tests.", "Lance les tests.", "Führe die Tests aus.", "Esegui i test.", "テストを実行してください。", "테스트를 실행해 주세요.", "运行测试。", "टेस्ट चलाइए।", "Testleri çalıştır."),
("Nice, the tests pass.", "Confirming all tests are green after a change", "Legal, os testes passaram.", "Bien, los tests pasan.", "Super, les tests passent.", "Schön, die Tests laufen durch.", "Bene, i test passano.", "いいですね、テストが通りました。", "좋아요, 테스트가 통과했어요.", "不错，测试通过了。", "बढ़िया, टेस्ट पास हो गए।", "Güzel, testler geçiyor."),
("That test is failing.", "Pointing out a failed test during pairing", "Esse teste está falhando.", "Ese test está fallando.", "Ce test échoue.", "Der Test schlägt fehl.", "Quel test sta fallendo.", "そのテストが失敗しています。", "그 테스트가 실패하고 있어요.", "那个测试失败了。", "वो टेस्ट फेल हो रहा है।", "O test başarısız oluyor."),
("Let me type this part.", "Asking to take over as the driver for a section", "Deixa eu digitar essa parte.", "Déjame escribir esta parte.", "Laisse-moi taper cette partie.", "Lass mich diesen Teil tippen.", "Fammi scrivere questa parte.", "この部分は私がタイプします。", "이 부분은 제가 타이핑할게요.", "这部分让我来打。", "यह हिस्सा मुझे टाइप करने दीजिए।", "Bu kısmı ben yazayım."),
("What do you think?", "Asking the navigator for their opinion on an approach", "O que você acha?", "¿Qué opinas?", "Qu'est-ce que tu en penses ?", "Was denkst du?", "Cosa ne pensi?", "どう思いますか？", "어떻게 생각하세요?", "你觉得怎么样？", "आप क्या सोचते हैं?", "Ne düşünüyorsun?"),
("Sounds good to me.", "Agreeing with a suggested approach", "Parece bom pra mim.", "Me parece bien.", "Ça me va.", "Klingt gut.", "Mi sembra buono.", "いいと思います。", "저도 좋아요.", "听起来不错。", "मुझे ठीक लगता है।", "Bana iyi görünüyor."),
("Good catch!", "Praising the navigator for spotting an error", "Boa pegada!", "¡Buena observación!", "Bien vu !", "Gut erkannt!", "Ben trovato!", "いい発見ですね！", "잘 잡았어요!", "发现得好！", "अच्छी पकड़!", "İyi yakaladın!"),
("I missed that, thanks.", "Thanking the navigator for catching something you overlooked", "Eu não vi isso, obrigado.", "Se me pasó, gracias.", "Je l'avais raté, merci.", "Das habe ich übersehen, danke.", "Mi era sfuggito, grazie.", "見逃していました、ありがとう。", "놓쳤었네요, 감사합니다.", "我没注意到，谢谢。", "मैंने वो मिस कर दिया, धन्यवाद।", "Onu kaçırmışım, teşekkürler."),
("Let's take a break.", "Suggesting a pause during a long pairing session", "Vamos fazer uma pausa.", "Tomemos un descanso.", "Faisons une pause.", "Lass uns eine Pause machen.", "Facciamo una pausa.", "休憩しましょう。", "잠깐 쉬어요.", "我们休息一下吧。", "चलिए ब्रेक लेते हैं।", "Bir mola verelim."),
("Five-minute break?", "Proposing a short break during pairing", "Pausa de cinco minutos?", "¿Cinco minutos de descanso?", "Pause de cinq minutes ?", "Fünf Minuten Pause?", "Pausa di cinque minuti?", "5分休憩しますか？", "5분 쉴까요?", "休息五分钟？", "पांच मिनट का ब्रेक?", "Beş dakika mola mı?"),
("I'm back.", "Returning after a break during a pairing session", "Voltei.", "Ya volví.", "Je suis de retour.", "Ich bin wieder da.", "Sono tornato.", "戻りました。", "돌아왔어요.", "我回来了。", "मैं वापस आ गया।", "Döndüm."),
("Ready to continue?", "Checking if the pair is ready to resume after a break", "Pronto pra continuar?", "¿Listo para continuar?", "Prêt à continuer ?", "Bereit weiterzumachen?", "Pronto a continuare?", "続けましょうか？", "계속할 준비됐어요?", "准备好继续了吗？", "जारी रखने के लिए तैयार?", "Devam etmeye hazır mısın?"),
("Where were we?", "Picking up after a break or interruption", "Onde paramos?", "¿Dónde estábamos?", "On en était où ?", "Wo waren wir?", "Dove eravamo rimasti?", "どこまでやりましたっけ？", "어디까지 했었죠?", "我们刚才到哪了？", "हम कहां थे?", "Nerede kalmıştık?"),
("Can you hear me okay?", "Checking audio at the start of a remote pairing session", "Você me ouve bem?", "¿Me escuchas bien?", "Tu m'entends bien ?", "Hörst du mich gut?", "Mi senti bene?", "聞こえますか？", "제 목소리 잘 들려요?", "你能听到我吗？", "क्या आप मुझे सुन पा रहे हैं?", "Beni iyi duyabiliyor musun?"),
("You're on mute.", "Telling the other person their microphone is muted", "Você está no mudo.", "Estás en silencio.", "Tu es en sourdine.", "Du bist auf stumm.", "Sei in muto.", "ミュートになっていますよ。", "음소거 상태예요.", "你静音了。", "आप म्यूट पर हैं।", "Sesini kapatmışsın."),
("Sorry, I was on mute.", "Apologizing after realizing you were muted", "Desculpa, eu estava no mudo.", "Perdón, estaba en silencio.", "Désolé, j'étais en sourdine.", "Sorry, ich war auf stumm.", "Scusa, ero in muto.", "すみません、ミュートでした。", "죄송해요, 음소거였어요.", "抱歉，我刚才静音了。", "सॉरी, मैं म्यूट पर था।", "Pardon, sesimi kapatmışım."),
("Let me pull up that file.", "Navigating to a specific file during pairing", "Deixa eu abrir esse arquivo.", "Déjame abrir ese archivo.", "Laisse-moi ouvrir ce fichier.", "Lass mich die Datei öffnen.", "Fammi aprire quel file.", "そのファイルを開きますね。", "그 파일을 열어볼게요.", "我来打开那个文件。", "मैं वो फ़ाइल खोलता हूं।", "O dosyayı açayım."),
("What line is that on?", "Asking which line number to look at", "Em qual linha está?", "¿En qué línea está?", "C'est à quelle ligne ?", "In welcher Zeile ist das?", "A che riga è?", "何行目ですか？", "몇 번째 줄이에요?", "在第几行？", "वो किस लाइन पर है?", "Hangi satırda?"),
("Let me look at the error.", "Examining an error message during debugging", "Deixa eu ver o erro.", "Déjame ver el error.", "Laisse-moi regarder l'erreur.", "Lass mich den Fehler ansehen.", "Fammi guardare l'errore.", "エラーを見てみます。", "에러를 살펴볼게요.", "让我看看这个错误。", "मुझे एरर देखने दीजिए।", "Hataya bir bakayım."),
("Try running it again.", "Suggesting to re-run the code after a fix", "Tenta rodar de novo.", "Intenta ejecutarlo de nuevo.", "Essaie de le relancer.", "Versuch es nochmal auszuführen.", "Prova a eseguirlo di nuovo.", "もう一度実行してみてください。", "다시 실행해 보세요.", "再运行一次试试。", "फिर से चलाकर देखिए।", "Tekrar çalıştırmayı dene."),
("That fixed it!", "Celebrating when a bug is resolved", "Isso resolveu!", "¡Eso lo arregló!", "Ça l'a corrigé !", "Das hat es behoben!", "Questo l'ha risolto!", "直りました！", "고쳐졌어요!", "修好了！", "ठीक हो गया!", "Düzeldi!"),
("Wait, go back.", "Asking the driver to undo or scroll back", "Espera, volta.", "Espera, vuelve.", "Attends, reviens en arrière.", "Warte, geh zurück.", "Aspetta, torna indietro.", "待って、戻してください。", "잠깐, 돌아가 주세요.", "等等，回去。", "रुकिए, वापस जाइए।", "Dur, geri dön."),
("Undo that change.", "Asking the driver to revert a recent edit", "Desfaz essa mudança.", "Deshaz ese cambio.", "Annule ce changement.", "Mach die Änderung rückgängig.", "Annulla quella modifica.", "その変更を元に戻してください。", "그 변경을 취소해 주세요.", "撤销那个修改。", "वो बदलाव अनडू कीजिए।", "O değişikliği geri al."),
("Save the file.", "Reminding the driver to save", "Salva o arquivo.", "Guarda el archivo.", "Sauvegarde le fichier.", "Speichere die Datei.", "Salva il file.", "ファイルを保存してください。", "파일을 저장하세요.", "保存文件。", "फ़ाइल सेव कीजिए।", "Dosyayı kaydet."),
("Let's commit this.", "Suggesting to commit the current changes", "Vamos commitar isso.", "Vamos hacer commit de esto.", "Faisons un commit.", "Lass uns das committen.", "Facciamo il commit.", "コミットしましょう。", "커밋합시다.", "我们提交一下吧。", "चलिए इसे कमिट करते हैं।", "Bunu commit edelim."),
("Should we push this?", "Asking if the changes should be pushed to remote", "Devemos dar push nisso?", "¿Lo subimos?", "On pousse ça ?", "Sollen wir das pushen?", "Lo pushiamo?", "プッシュしますか？", "푸시할까요?", "要推送吗？", "क्या इसे पुश करें?", "Bunu push edelim mi?"),
("Hold on, let me think.", "Asking for a moment to think during pairing", "Espera, deixa eu pensar.", "Espera, déjame pensar.", "Attends, laisse-moi réfléchir.", "Moment, lass mich nachdenken.", "Aspetta, fammi pensare.", "ちょっと待って、考えさせて。", "잠깐, 생각해볼게요.", "等一下，让我想想。", "रुकिए, मुझे सोचने दीजिए।", "Dur, düşüneyim."),
("That makes sense.", "Agreeing with an explanation during pairing", "Faz sentido.", "Tiene sentido.", "Ça a du sens.", "Das macht Sinn.", "Ha senso.", "なるほど。", "이해가 돼요.", "有道理。", "समझ में आया।", "Mantıklı."),
("I see what you mean.", "Understanding the navigator's suggestion", "Entendi o que você quer dizer.", "Entiendo lo que dices.", "Je vois ce que tu veux dire.", "Ich verstehe, was du meinst.", "Capisco cosa intendi.", "言いたいことがわかりました。", "무슨 말인지 알겠어요.", "我明白你的意思了。", "मैं समझ गया आप क्या कह रहे हैं।", "Ne demek istediğini anlıyorum."),
("Can you explain that?", "Asking the navigator to clarify a suggestion", "Pode explicar isso?", "¿Puedes explicar eso?", "Tu peux expliquer ça ?", "Kannst du das erklären?", "Puoi spiegare?", "説明してもらえますか？", "그거 설명해 줄 수 있어요?", "你能解释一下吗？", "क्या आप वो समझा सकते हैं?", "Bunu açıklayabilir misin?"),
("I'm not sure about that.", "Expressing uncertainty about an approach", "Não tenho certeza sobre isso.", "No estoy seguro de eso.", "Je ne suis pas sûr de ça.", "Da bin ich mir nicht sicher.", "Non ne sono sicuro.", "それはちょっと確信が持てません。", "그건 좀 확신이 안 서요.", "我不太确定。", "मुझे इसके बारे में पक्का नहीं है।", "Bundan emin değilim."),
("Let's try it and see.", "Suggesting an experimental approach", "Vamos tentar e ver.", "Probemos y veamos.", "Essayons et voyons.", "Lass uns das ausprobieren.", "Proviamo e vediamo.", "試してみましょう。", "해보고 봐요.", "试试看吧。", "चलिए कोशिश करके देखते हैं।", "Deneyelim ve görelim."),
("That looks right.", "Confirming the code looks correct", "Parece certo.", "Eso se ve bien.", "Ça a l'air correct.", "Das sieht richtig aus.", "Sembra corretto.", "正しそうですね。", "맞아 보여요.", "看起来对了。", "सही लग रहा है।", "Doğru görünüyor."),
("Check the console.", "Directing attention to console output", "Olha no console.", "Mira la consola.", "Regarde la console.", "Schau in die Konsole.", "Controlla la console.", "コンソールを確認してください。", "콘솔을 확인해 보세요.", "看一下控制台。", "कंसोल चेक कीजिए।", "Konsola bak."),
("There's a typo there.", "Spotting a spelling mistake in the code", "Tem um erro de digitação ali.", "Hay un error tipográfico ahí.", "Il y a une faute de frappe.", "Da ist ein Tippfehler.", "C'è un errore di battitura.", "タイプミスがありますよ。", "오타가 있어요.", "那里有个拼写错误。", "वहां एक टाइपो है।", "Orada bir yazım hatası var."),
("You're missing a semicolon.", "Pointing out a missing semicolon", "Faltou um ponto e vírgula.", "Te falta un punto y coma.", "Il manque un point-virgule.", "Da fehlt ein Semikolon.", "Manca un punto e virgola.", "セミコロンが抜けています。", "세미콜론이 빠졌어요.", "少了一个分号。", "सेमीकोलन छूट गया है।", "Bir noktalı virgül eksik."),
("Close that bracket.", "Reminding the driver about an unclosed bracket", "Fecha esse parêntese.", "Cierra ese paréntesis.", "Ferme cette parenthèse.", "Schließe die Klammer.", "Chiudi quella parentesi.", "その括弧を閉じてください。", "그 괄호를 닫아주세요.", "把那个括号关上。", "वो ब्रैकेट बंद कीजिए।", "O parantezi kapat."),
("Add a space there.", "Suggesting formatting improvement", "Coloca um espaço ali.", "Agrega un espacio ahí.", "Ajoute un espace là.", "Füge da ein Leerzeichen ein.", "Aggiungi uno spazio lì.", "そこにスペースを入れてください。", "거기에 공백을 넣어주세요.", "那里加个空格。", "वहां एक स्पेस डालिए।", "Oraya bir boşluk ekle."),
("What does that function do?", "Asking about an unfamiliar function", "O que essa função faz?", "¿Qué hace esa función?", "Elle fait quoi cette fonction ?", "Was macht diese Funktion?", "Cosa fa quella funzione?", "その関数は何をしますか？", "그 함수는 뭘 하는 거예요?", "那个函数是做什么的？", "वो फ़ंक्शन क्या करता है?", "O fonksiyon ne yapıyor?"),
("Where is that defined?", "Asking where a variable or function is declared", "Onde isso é definido?", "¿Dónde está definido eso?", "C'est défini où ça ?", "Wo ist das definiert?", "Dove è definito?", "それはどこで定義されていますか？", "그건 어디에 정의되어 있어요?", "那是在哪里定义的？", "वो कहां डिफ़ाइन है?", "Nerede tanımlanmış?"),
("Let me search for that.", "Using search to find something in the codebase", "Deixa eu procurar isso.", "Déjame buscar eso.", "Laisse-moi chercher ça.", "Lass mich danach suchen.", "Fammi cercare.", "検索してみますね。", "그걸 찾아볼게요.", "让我搜一下。", "मुझे वो ढूंढने दीजिए।", "Onu bir arayım."),
("Found it.", "Locating something in the code", "Achei.", "Lo encontré.", "Trouvé.", "Gefunden.", "Trovato.", "見つけました。", "찾았어요.", "找到了。", "मिल गया।", "Buldum."),
("I'm lost. Where are we?", "Feeling disoriented in the codebase during pairing", "Me perdi. Onde estamos?", "Estoy perdido. ¿Dónde estamos?", "Je suis perdu. On est où ?", "Ich bin verloren. Wo sind wir?", "Mi sono perso. Dove siamo?", "わからなくなりました。今どこですか？", "길을 잃었어요. 어디에 있는 거예요?", "我迷路了，我们在哪？", "मैं खो गया। हम कहां हैं?", "Kayboldum. Neredeyiz?"),
("This is getting complex.", "Acknowledging increasing complexity during pairing", "Isso está ficando complexo.", "Esto se está poniendo complejo.", "Ça devient complexe.", "Das wird komplex.", "Sta diventando complesso.", "複雑になってきましたね。", "점점 복잡해지고 있어요.", "这变得复杂了。", "ये जटिल हो रहा है।", "Bu karmaşıklaşıyor."),
("Let's keep it simple.", "Advocating for a simpler approach", "Vamos manter simples.", "Mantengámoslo simple.", "Gardons ça simple.", "Halten wir es einfach.", "Teniamolo semplice.", "シンプルにいきましょう。", "단순하게 가요.", "保持简单吧。", "चलिए इसे सिंपल रखते हैं।", "Basit tutalım."),
("One step at a time.", "Suggesting an incremental approach", "Um passo de cada vez.", "Paso a paso.", "Une étape à la fois.", "Eins nach dem anderen.", "Un passo alla volta.", "一歩ずつやりましょう。", "한 번에 한 단계씩요.", "一步一步来。", "एक बार में एक कदम।", "Adım adım gidelim."),
("Let's start with a test.", "Suggesting test-driven development", "Vamos começar com um teste.", "Empecemos con un test.", "Commençons par un test.", "Fangen wir mit einem Test an.", "Iniziamo con un test.", "テストから始めましょう。", "테스트부터 시작해요.", "先写个测试吧。", "चलिए एक टेस्ट से शुरू करते हैं।", "Bir testle başlayalım."),
("Write the test first.", "Encouraging TDD during pairing", "Escreve o teste primeiro.", "Escribe el test primero.", "Écris le test d'abord.", "Schreib zuerst den Test.", "Scrivi prima il test.", "先にテストを書きましょう。", "테스트를 먼저 작성하세요.", "先写测试。", "पहले टेस्ट लिखिए।", "Önce testi yaz."),
]

for i, d in enumerate(data_easy_1, 1):
    phrases.append({
        "id": f"pairProgramming_{i:03d}",
        "english": d[0],
        "context": d[1],
        "translations": {
            "pt-BR": d[2], "es": d[3], "fr": d[4], "de": d[5],
            "it": d[6], "ja": d[7], "ko": d[8], "zh-Hans": d[9],
            "hi": d[10], "tr": d[11]
        },
        "difficulty": "easy",
        "category": "pairProgramming"
    })

print(f"After batch 1: {len(phrases)} phrases")

# ============================================================
# EASY PHRASES 61-120: Thinking aloud, suggesting, asking
# ============================================================
data_easy_2 = [
("I'm thinking out loud here.", "Verbalizing your thought process for the navigator", "Estou pensando em voz alta.", "Estoy pensando en voz alta.", "Je pense tout haut.", "Ich denke laut nach.", "Sto pensando ad alta voce.", "考えを声に出しています。", "생각을 소리내어 말하고 있어요.", "我在自言自语想思路。", "मैं ज़ोर से सोच रहा हूं।", "Sesli düşünüyorum."),
("So the idea is...", "Beginning to explain your approach", "Então a ideia é...", "La idea es...", "Donc l'idée c'est...", "Also die Idee ist...", "Quindi l'idea è...", "つまりアイデアは…", "그러니까 아이디어는...", "想法是这样的……", "तो विचार यह है...", "Yani fikir şu..."),
("What if we try this?", "Proposing an alternative approach", "E se a gente tentar isso?", "¿Y si probamos esto?", "Et si on essayait ça ?", "Was, wenn wir das versuchen?", "E se proviamo questo?", "これを試してみたらどうですか？", "이렇게 해보면 어떨까요?", "我们试试这个怎么样？", "अगर हम ये try करें तो?", "Bunu denersek ne olur?"),
("How about this approach?", "Suggesting a different way to solve the problem", "Que tal essa abordagem?", "¿Qué tal este enfoque?", "Que penses-tu de cette approche ?", "Wie wäre es mit diesem Ansatz?", "Che ne dici di questo approccio?", "このアプローチはどうですか？", "이 접근법은 어때요?", "这个方法怎么样？", "इस अप्रोच के बारे में क्या ख्याल है?", "Bu yaklaşım nasıl olur?"),
("I have an idea.", "Introducing a new suggestion", "Tenho uma ideia.", "Tengo una idea.", "J'ai une idée.", "Ich habe eine Idee.", "Ho un'idea.", "アイデアがあります。", "아이디어가 있어요.", "我有个想法。", "मेरे पास एक आइडिया है।", "Bir fikrim var."),
("Let's try a different way.", "Suggesting a change in approach after getting stuck", "Vamos tentar de outro jeito.", "Intentemos de otra forma.", "Essayons autrement.", "Lass uns einen anderen Weg versuchen.", "Proviamo in un altro modo.", "別の方法を試しましょう。", "다른 방법으로 해봐요.", "换个方法试试吧。", "चलिए दूसरे तरीके से try करते हैं।", "Farklı bir yol deneyelim."),
("That won't work because...", "Explaining why a suggested approach has issues", "Isso não vai funcionar porque...", "Eso no va a funcionar porque...", "Ça ne marchera pas parce que...", "Das wird nicht funktionieren, weil...", "Non funzionerà perché...", "それはうまくいかないです、なぜなら…", "그건 안 될 거예요, 왜냐하면...", "那样行不通，因为……", "वो काम नहीं करेगा क्योंकि...", "O işe yaramaz çünkü..."),
("Actually, wait.", "Pausing to reconsider an approach", "Na verdade, espera.", "En realidad, espera.", "En fait, attends.", "Eigentlich, warte.", "In realtà, aspetta.", "あ、ちょっと待ってください。", "아, 잠깐만요.", "等一下，其实……", "दरअसल, रुकिए।", "Aslında, dur bir dakika."),
("Never mind, that's fine.", "Withdrawing a concern after reconsideration", "Esquece, tá bom assim.", "Olvídalo, está bien.", "Laisse tomber, c'est bon.", "Vergiss es, das ist okay.", "Lascia stare, va bene.", "やっぱりいいです、大丈夫です。", "아, 됐어요, 괜찮아요.", "算了，没事。", "छोड़िए, ठीक है।", "Boşver, sorun yok."),
("Right, I see.", "Acknowledging understanding", "Certo, entendi.", "Claro, ya veo.", "D'accord, je vois.", "Richtig, ich verstehe.", "Giusto, capisco.", "なるほど、わかりました。", "네, 알겠어요.", "嗯，我明白了。", "हां, समझ गया।", "Tamam, anlıyorum."),
("Exactly.", "Confirming the navigator's understanding", "Exatamente.", "Exacto.", "Exactement.", "Genau.", "Esattamente.", "その通りです。", "맞아요.", "没错。", "बिल्कुल।", "Aynen öyle."),
("That's a good point.", "Acknowledging a valid observation from the navigator", "Bom ponto.", "Buen punto.", "C'est un bon point.", "Das ist ein guter Punkt.", "Buon punto.", "いい指摘ですね。", "좋은 지적이에요.", "说得好。", "अच्छी बात है।", "İyi bir nokta."),
("Let me read this code first.", "Asking for a moment to understand existing code", "Deixa eu ler esse código primeiro.", "Déjame leer este código primero.", "Laisse-moi lire ce code d'abord.", "Lass mich den Code zuerst lesen.", "Fammi leggere questo codice prima.", "まずこのコードを読ませてください。", "먼저 이 코드를 읽어볼게요.", "让我先看看这段代码。", "पहले मुझे ये कोड पढ़ने दीजिए।", "Önce bu kodu bir okuyayım."),
("I need a minute to understand this.", "Asking for time to comprehend complex code", "Preciso de um minuto pra entender isso.", "Necesito un minuto para entender esto.", "J'ai besoin d'une minute pour comprendre.", "Ich brauche eine Minute, um das zu verstehen.", "Mi serve un minuto per capire.", "理解するのに少し時間をください。", "이해하는 데 잠깐 시간이 필요해요.", "我需要一分钟理解一下。", "मुझे समझने के लिए एक मिनट चाहिए।", "Bunu anlamak için bir dakikaya ihtiyacım var."),
("Walk me through this.", "Asking the other person to explain the code step by step", "Me explica isso passo a passo.", "Explícame esto paso a paso.", "Explique-moi ça étape par étape.", "Erkläre mir das Schritt für Schritt.", "Spiegamelo passo per passo.", "これを順に説明してもらえますか？", "이거 하나씩 설명해 주세요.", "给我讲讲这段代码。", "मुझे स्टेप बाय स्टेप बताइए।", "Bunu bana adım adım anlat."),
("Got it, go ahead.", "Signaling understanding and readiness to proceed", "Entendi, pode ir.", "Entendido, adelante.", "Compris, vas-y.", "Verstanden, mach weiter.", "Capito, vai pure.", "わかりました、続けてください。", "알겠어요, 계속하세요.", "明白了，继续吧。", "समझ गया, आगे बढ़िए।", "Anladım, devam et."),
("What are we trying to do here?", "Clarifying the goal of the current task", "O que estamos tentando fazer aqui?", "¿Qué intentamos hacer aquí?", "Qu'est-ce qu'on essaie de faire ici ?", "Was versuchen wir hier zu tun?", "Cosa stiamo cercando di fare qui?", "ここで何をしようとしていますか？", "여기서 뭘 하려는 거예요?", "我们这里要做什么？", "यहां हम क्या करने की कोशिश कर रहे हैं?", "Burada ne yapmaya çalışıyoruz?"),
("Let me check the docs.", "Looking up documentation during pairing", "Deixa eu olhar a documentação.", "Déjame revisar la documentación.", "Laisse-moi vérifier la doc.", "Lass mich die Doku prüfen.", "Fammi controllare la documentazione.", "ドキュメントを確認させてください。", "문서를 확인해 볼게요.", "让我查一下文档。", "मुझे डॉक्स चेक करने दीजिए।", "Dokümantasyona bir bakayım."),
("I'll look that up.", "Offering to research something unknown", "Vou pesquisar isso.", "Voy a buscarlo.", "Je vais chercher ça.", "Ich schaue das nach.", "Lo cerco.", "調べてみます。", "찾아볼게요.", "我查一下。", "मैं वो देख लेता हूं।", "Onu bir araştırayım."),
("Do you know this library?", "Asking about familiarity with a dependency", "Você conhece essa biblioteca?", "¿Conoces esta librería?", "Tu connais cette bibliothèque ?", "Kennst du diese Bibliothek?", "Conosci questa libreria?", "このライブラリを知っていますか？", "이 라이브러리 아세요?", "你了解这个库吗？", "क्या आप इस लाइब्रेरी को जानते हैं?", "Bu kütüphaneyi biliyor musun?"),
("Let's add a comment here.", "Suggesting documentation in the code", "Vamos adicionar um comentário aqui.", "Agreguemos un comentario aquí.", "Ajoutons un commentaire ici.", "Lass uns hier einen Kommentar hinzufügen.", "Aggiungiamo un commento qui.", "ここにコメントを追加しましょう。", "여기에 주석을 추가해요.", "在这里加个注释吧。", "यहां एक कमेंट डालते हैं।", "Buraya bir yorum ekleyelim."),
("Name this variable better.", "Suggesting a more descriptive variable name", "Dá um nome melhor pra essa variável.", "Ponle un mejor nombre a esta variable.", "Renomme cette variable.", "Benenne diese Variable besser.", "Dai un nome migliore a questa variabile.", "この変数名をもっと良くしましょう。", "이 변수 이름을 더 좋게 바꿔요.", "给这个变量起个更好的名字。", "इस वेरिएबल का बेहतर नाम रखिए।", "Bu değişkene daha iyi bir isim ver."),
("This needs a refactor.", "Identifying code that should be refactored", "Isso precisa de um refactor.", "Esto necesita un refactor.", "Ça a besoin d'un refactoring.", "Das braucht ein Refactoring.", "Questo ha bisogno di un refactoring.", "これはリファクタリングが必要です。", "이건 리팩토링이 필요해요.", "这需要重构。", "इसे रिफैक्टर करना होगा।", "Bunun yeniden düzenlenmesi gerekiyor."),
("Let's clean this up later.", "Deferring refactoring to stay focused", "Vamos limpar isso depois.", "Limpiemos esto después.", "On nettoiera ça plus tard.", "Lass uns das später aufräumen.", "Puliamo dopo.", "後できれいにしましょう。", "나중에 정리해요.", "这个以后再清理。", "इसे बाद में साफ़ करते हैं।", "Bunu sonra temizleyelim."),
("I'll add a TODO.", "Marking code for future work", "Vou adicionar um TODO.", "Voy a agregar un TODO.", "Je vais ajouter un TODO.", "Ich füge ein TODO hinzu.", "Aggiungo un TODO.", "TODOを追加しておきます。", "TODO를 추가할게요.", "我加个TODO。", "मैं एक TODO डालता हूं।", "Bir TODO ekleyeceğim."),
("Does this look okay?", "Asking for validation on written code", "Isso parece bom?", "¿Esto se ve bien?", "Ça a l'air bon ?", "Sieht das okay aus?", "Va bene così?", "これは大丈夫そうですか？", "이거 괜찮아 보여요?", "这样可以吗？", "ये ठीक लग रहा है?", "Bu iyi görünüyor mu?"),
("Perfect, let's move on.", "Agreeing the current task is done", "Perfeito, vamos em frente.", "Perfecto, sigamos.", "Parfait, passons à la suite.", "Perfekt, lass uns weitermachen.", "Perfetto, andiamo avanti.", "完璧、次に進みましょう。", "완벽해요, 다음으로 넘어가요.", "完美，继续吧。", "परफेक्ट, आगे बढ़ते हैं।", "Mükemmel, devam edelim."),
("What's next?", "Asking about the next task after completing one", "O que vem agora?", "¿Qué sigue?", "C'est quoi la suite ?", "Was kommt als Nächstes?", "Cosa viene dopo?", "次は何ですか？", "다음은 뭐예요?", "接下来做什么？", "अगला क्या है?", "Sırada ne var?"),
("We're making good progress.", "Encouraging the pair during a session", "Estamos progredindo bem.", "Estamos avanzando bien.", "On avance bien.", "Wir machen gute Fortschritte.", "Stiamo facendo buoni progressi.", "順調に進んでいますね。", "잘 진행되고 있어요.", "我们进展不错。", "हम अच्छी प्रगति कर रहे हैं।", "İyi ilerliyoruz."),
("Almost there.", "Encouraging the pair when close to finishing", "Quase lá.", "Ya casi.", "On y est presque.", "Fast geschafft.", "Ci siamo quasi.", "もうすぐです。", "거의 다 됐어요.", "快好了。", "लगभग हो गया।", "Neredeyse tamam."),
("Let me try something.", "Asking to experiment with a solution", "Deixa eu tentar uma coisa.", "Déjame intentar algo.", "Laisse-moi essayer un truc.", "Lass mich etwas versuchen.", "Fammi provare una cosa.", "ちょっと試してみていいですか。", "뭔가 해볼게요.", "让我试试。", "मुझे कुछ try करने दीजिए।", "Bir şey deneyeyim."),
("Wait, I think I see the bug.", "Spotting an issue while debugging together", "Espera, acho que vi o bug.", "Espera, creo que veo el bug.", "Attends, je crois que je vois le bug.", "Warte, ich glaube ich sehe den Bug.", "Aspetta, credo di vedere il bug.", "待って、バグが見えたかも。", "잠깐, 버그가 보이는 것 같아요.", "等等，我好像看到bug了。", "रुकिए, मुझे लगता है बग दिख गया।", "Dur, hatayı gördüm galiba."),
("It's this line right here.", "Pointing to the specific line causing an issue", "É nessa linha aqui.", "Es esta línea de aquí.", "C'est cette ligne-là.", "Es ist diese Zeile hier.", "È questa riga qui.", "この行です。", "바로 이 줄이에요.", "就是这一行。", "यही लाइन है।", "İşte bu satır."),
("Ah, I see the problem.", "Identifying the root cause of a bug", "Ah, estou vendo o problema.", "Ah, veo el problema.", "Ah, je vois le problème.", "Ah, ich sehe das Problem.", "Ah, vedo il problema.", "あ、問題がわかりました。", "아, 문제가 보여요.", "啊，我看到问题了。", "आह, मुझे प्रॉब्लम दिख गई।", "Ah, sorunu görüyorum."),
("Can you try that shortcut?", "Suggesting a keyboard shortcut to the driver", "Pode tentar esse atalho?", "¿Puedes probar ese atajo?", "Tu peux essayer ce raccourci ?", "Kannst du die Tastenkombination probieren?", "Puoi provare quella scorciatoia?", "そのショートカットを試してみて。", "그 단축키를 써볼래요?", "你试试那个快捷键？", "वो शॉर्टकट try कीजिए?", "O kısayolu dener misin?"),
("Nice, that's clean.", "Complimenting clean code during review", "Legal, ficou limpo.", "Genial, está limpio.", "Super, c'est propre.", "Schön, das ist sauber.", "Bello, è pulito.", "いいですね、きれいです。", "좋아요, 깔끔해요.", "不错，很干净。", "बढ़िया, ये साफ़ है।", "Güzel, temiz olmuş."),
("I like that solution.", "Expressing approval of a coding approach", "Gostei dessa solução.", "Me gusta esa solución.", "J'aime cette solution.", "Die Lösung gefällt mir.", "Mi piace quella soluzione.", "その解決法いいですね。", "그 솔루션 마음에 들어요.", "我喜欢这个方案。", "मुझे वो सॉल्यूशन पसंद है।", "Bu çözümü beğendim."),
("That's a clever trick.", "Admiring an elegant coding technique", "Esse é um truque esperto.", "Ese es un truco ingenioso.", "C'est une astuce ingénieuse.", "Das ist ein cleverer Trick.", "È un trucco intelligente.", "それは賢いテクニックですね。", "영리한 트릭이네요.", "这个技巧很巧妙。", "ये एक स्मार्ट ट्रिक है।", "Bu akıllıca bir numara."),
("High five!", "Celebrating after solving a tough problem together", "Toca aqui!", "¡Choca esos cinco!", "Tape-la !", "High five!", "Batti cinque!", "ハイタッチ！", "하이파이브!", "击掌！", "हाई फ़ाइव!", "Çak bir beşlik!"),
]

for i, d in enumerate(data_easy_2, 61):
    phrases.append({
        "id": f"pairProgramming_{i:03d}",
        "english": d[0],
        "context": d[1],
        "translations": {
            "pt-BR": d[2], "es": d[3], "fr": d[4], "de": d[5],
            "it": d[6], "ja": d[7], "ko": d[8], "zh-Hans": d[9],
            "hi": d[10], "tr": d[11]
        },
        "difficulty": "easy",
        "category": "pairProgramming"
    })

print(f"After batch 2: {len(phrases)} phrases")

# Save checkpoint
with open("/Users/joaoflores/Documents/GambitStudio/DevLingo/gen_pair_checkpoint.json", "w") as f:
    json.dump(phrases, f)
print("Checkpoint saved")
